### ISSUE TITLE
iOS13 crashed

### ISSUE THREAD

**Issue by ZaggerWang** [Azure/azure-notificationhubs-ios#32] opened 2019-09-06 02:54 UTC
iOS13 `registerNativeWithDeviceToken` method crashed

**Comment by brannon** [comment] 2019-09-06 05:14
@zaggerwang this is a duplicate of #30. We are busy getting a new release ready that fixes this issue:
https://github.com/Azure/azure-notificationhubs-ios/releases/tag/2.0.4

It should be available in CocoaPods soon. Or you can download the framework from the release files.

**Closed by brannon** 2019-09-06 05:14 UTC

**Comment by brannon** [comment] 2019-09-14 06:27
The updated pod has been published (version 2.0.4)
