### ISSUE TITLE
iOS 13 crash on registerNativeWithDeviceToken & unregisterNativeWithDeviceToken

### ISSUE THREAD

**Issue by kross50** [Azure/azure-notificationhubs-ios#30] opened 2019-06-17 16:03 UTC

**Comment by kross50** [comment] 2019-06-21 05:24
Issue happens on iOS 13 Beta 1 & Beta 2 still.

**Comment by jwargo** [comment] 2019-06-25 13:54
@kross50 Can you please provide more information? Telling us your app crashed without providing code samples and error messages doesn't allow us to provide you with any assistance.

**Comment by kross51** [comment] 2019-06-28 03:26
Sorry, couldn't recover my old account.  At any rate, the following is the code snippet and below that is the exception.

SBNotificationHub* hub = [[SBNotificationHub alloc] initWithConnectionString:HUBLISTENACCESS_PROD
                                                          notificationHubPath:HUBNAME_PROD]

[hub registerNativeWithDeviceToken:deviceToken tags:[NSSet setWithArray:@[convertedDeviceToken]] completion:^(NSError* error) {
....
}];

oPHOTO`+[SBNotificationHubHelper signString:withKeyData:keyLength:]:
    0x1035da75c <+0>:   sub    sp, sp, #0x70             ; =0x70 
    0x1035da760 <+4>:   stp    x24, x23, [sp, #0x30]
    0x1035da764 <+8>:   stp    x22, x21, [sp, #0x40]
    0x1035da768 <+12>:  stp    x20, x19, [sp, #0x50]
    0x1035da76c <+16>:  stp    x29, x30, [sp, #0x60]
    0x1035da770 <+20>:  add    x29, sp, #0x60            ; =0x60 
    0x1035da774 <+24>:  mov    x20, x4
    0x1035da778 <+28>:  mov    x21, x3
    0x1035da77c <+32>:  mov    x22, x2
    0x1035da780 <+36>:  mov    x19, x0
    0x1035da784 <+40>:  adrp   x8, 2270
    0x1035da788 <+44>:  ldr    x8, [x8, #0x848]
    0x1035da78c <+48>:  ldr    x8, [x8]
    0x1035da790 <+52>:  str    x8, [sp, #0x28]
    0x1035da794 <+56>:  mov    x0, x22
    0x1035da798 <+60>:  bl     0x103c236b8               ; symbol stub for: objc_retain
    0x1035da79c <+64>:  mov    x23, x0
    0x1035da7a0 <+68>:  mov    x0, x22
    0x1035da7a4 <+72>:  bl     0x103c236c4               ; symbol stub for: objc_retainAutorelease
    0x1035da7a8 <+76>:  adrp   x8, 3022
    0x1035da7ac <+80>:  ldr    x1, [x8, #0x500]
    0x1035da7b0 <+84>:  orr    w2, wzr, #0x4
    0x1035da7b4 <+88>:  bl     0x103c23688               ; symbol stub for: objc_msgSend
    0x1035da7b8 <+92>:  mov    x22, x0
    0x1035da7bc <+96>:  mov    x0, x23
    0x1035da7c0 <+100>: bl     0x103c236ac               ; symbol stub for: objc_release
    0x1035da7c4 <+104>: mov    x0, x22
    0x1035da7c8 <+108>: bl     0x103c23d00               ; symbol stub for: strlen
->  0x1035da7cc <+112>: mov    x4, x0
    0x1035da7d0 <+116>: orr    w0, wzr, #0x2
    0x1035da7d4 <+120>: add    x5, sp, #0x8              ; =0x8 
    0x1035da7d8 <+124>: mov    x1, x21
    0x1035da7dc <+128>: mov    x2, x20
    0x1035da7e0 <+132>: mov    x3, x22
    0x1035da7e4 <+136>: bl     0x103c21a8c               ; symbol stub for: CCHmac
    0x1035da7e8 <+140>: adrp   x8, 3060
    0x1035da7ec <+144>: ldr    x0, [x8, #0x7f8]
    0x1035da7f0 <+148>: adrp   x8, 3020
    0x1035da7f4 <+152>: ldr    x1, [x8, #0x278]
    0x1035da7f8 <+156>: bl     0x103c23688               ; symbol stub for: objc_msgSend
    0x1035da7fc <+160>: adrp   x8, 3027
    0x1035da800 <+164>: ldr    x1, [x8, #0x1c0]
    0x1035da804 <+168>: add    x2, sp, #0x8              ; =0x8 
    0x1035da808 <+172>: orr    w3, wzr, #0x20
    0x1035da80c <+176>: bl     0x103c23688               ; symbol stub for: objc_msgSend
    0x1035da810 <+180>: bl     0x103c236c4               ; symbol stub for: objc_retainAutorelease
    0x1035da814 <+184>: mov    x20, x0
    0x1035da818 <+188>: adrp   x8, 3020
    0x1035da81c <+192>: ldr    x1, [x8, #0x948]
    0x1035da820 <+196>: bl     0x103c23688               ; symbol stub for: objc_msgSend
    0x1035da824 <+200>: mov    x21, x0
    0x1035da828 <+204>: adrp   x8, 3020
    0x1035da82c <+208>: ldr    x1, [x8, #0x290]
    0x1035da830 <+212>: mov    x0, x20
    0x1035da834 <+216>: bl     0x103c23688               ; symbol stub for: objc_msgSend
    0x1035da838 <+220>: mov    x3, x0
    0x1035da83c <+224>: adrp   x8, 3041
    0x1035da840 <+228>: ldr    x1, [x8, #0x7e0]
    0x1035da844 <+232>: mov    x0, x19
    0x1035da848 <+236>: mov    x2, x21
    0x1035da84c <+240>: bl     0x103c23688               ; symbol stub for: objc_msgSend
    0x1035da850 <+244>: mov    x29, x29
    0x1035da854 <+248>: bl     0x103c236dc               ; symbol stub for: objc_retainAutoreleasedReturnValue
    0x1035da858 <+252>: mov    x19, x0
    0x1035da85c <+256>: mov    x0, x20
    0x1035da860 <+260>: bl     0x103c236ac               ; symbol stub for: objc_release
    0x1035da864 <+264>: ldr    x8, [sp, #0x28]
    0x1035da868 <+268>: adrp   x9, 2270
    0x1035da86c <+272>: ldr    x9, [x9, #0x848]
    0x1035da870 <+276>: ldr    x9, [x9]
    0x1035da874 <+280>: sub    x8, x9, x8
    0x1035da878 <+284>: cbnz   x8, 0x1035da898           ; <+316> at SBNotificationHubHelper.m:48:1
    0x1035da87c <+288>: mov    x0, x19
    0x1035da880 <+292>: ldp    x29, x30, [sp, #0x60]
    0x1035da884 <+296>: ldp    x20, x19, [sp, #0x50]
    0x1035da888 <+300>: ldp    x22, x21, [sp, #0x40]
    0x1035da88c <+304>: ldp    x24, x23, [sp, #0x30]
    0x1035da890 <+308>: add    sp, sp, #0x70             ; =0x70 
    0x1035da894 <+312>: b      0x103c23574               ; symbol stub for: objc_autoreleaseReturnValue
    0x1035da898 <+316>: bl     0x103c22dac               ; symbol stub for: __stack_chk_fail

**Comment by kross51** [comment] 2019-06-28 03:28
This happens on iOS 13 Beta 1 & 2 but not iOS 12.x.x on iPhone XSMax, XS, X, ...

**Comment by kross51** [comment] 2019-06-28 03:30
![Screen Shot 2019-06-27 at 8 29 41 PM](https://user-images.githubusercontent.com/52305902/60315169-51146000-991a-11e9-9630-8603e18f9aca.png)

**Comment by kross51** [comment] 2019-06-28 03:30
![Screen Shot 2019-06-27 at 8 30 21 PM](https://user-images.githubusercontent.com/52305902/60315191-65585d00-991a-11e9-9500-0e420f9da2f0.png)

**Comment by varvusc** [comment] 2019-06-28 09:53
@kross51 unfortunately, we can't reproduce your issue. Could you please try to run any of our sample with your hubname and connection string and message us if the problem will reproduce?

**Comment by kross51** [comment] 2019-06-28 15:30
It appears the fix you guys just put in fixed my issue after I build the framework from master and updated that framework in my project.  Still testing but just wanted to give some quick feedback.

**Comment by varvusc** [comment] 2019-07-01 12:25
@kross51 I have closed this issue. Fill free to reopen if the issue will reproduced.

**Comment by arctouch-pedrocosta** [comment] 2019-08-16 17:55
@varvusc are you planning to make another release of the .framework so we can download it? Or, we will have to build from master from now on?

**Comment by brannon** [comment] 2019-09-06 05:16
@kross51 @arctouch-pedrocosta a new release should be available shortly:

https://github.com/Azure/azure-notificationhubs-ios/releases/tag/2.0.4

We will publish to CocoaPods as well.

**Comment by sjoerdsmink** [comment] 2019-09-11 11:00
@brannon Any update on when this update will be available on CocoaPods? I see that version 2.0.4 is released, but it's not available on https://cocoapods.org/pods/AzureNotificationHubs-iOS

**Comment by brannon** [comment] 2019-09-13 22:33
Sorry, working through some issues with publishing. We should have it resolved soon.

**Comment by brannon** [comment] 2019-09-14 06:27
The updated pod has been published (version 2.0.4)

**Comment by g0rp** [comment] 2019-09-19 12:45
Hi @brannon 
I just fetched 2.04 from pods and the issue Is still happening on iOS13.1 with Xcode 11.

Podfile.lock: - AzureNotificationHubs-iOS (2.0.4)

Issue:
`+[SBNotificationHubHelper signString:withKeyData:keyLength:]:`

Can it happen because of this change from Apple ?
https://twitter.com/_inside/status/1138478471590633473?s=20

**Comment by brannon** [comment] 2019-09-20 03:11
@g0rp can you provide more detail on the error you are seeing? For example, more of the call stack and the type of exception?

The issue you linked to was fixed in 2.0.4. We changed the way we are formatting the push token.

I'll try to reproduce your issue with our sample app, but getting more info would be helpful.

**Comment by brannon** [comment] 2019-09-24 17:16
Thanks for the additional info. I'm working on reproducing the issue.

**Comment by brannon** [comment] 2019-09-24 23:03
@David4FSU you should be able to use the `didRegisterForRemoteNotificationsWithDeviceToken` delegate handler. That handler is still called when the app registers for push notifications.

The `UNUserNotificationCenterDelegate` methods are used when receiving the push notifications themselves (not related to registration).

I haven't been able to reproduce the crash you are seeing. Can you double check that you have the latest `WindowsAzureMessaging.framework`?

The path you pasted in your call stack:
```
/Users/anefimov/Desktop/Work/azure-notificationhubs/iOS/WindowsAzureMessaging/WindowsAzureMessaging/Helpers/SBNotificationHubHelper.m:40
```
looks like it's referencing the old `azure-notificationhubs` repo, where the iOS SDK was previously located. We moved the SDK to this repo (`azure-notificationhubs-ios`). If you are somehow using the old framework then you won't have the fix we added for iOS 13.

If you are for sure using the latest framework, then I'll need some more information on how you are configuring the SDK. Based on the call stack you provided and a review of the code, it's possible that the `SBNotificationHub` object is being configured differently on iOS 13.

For what it's worth, I'm testing using the sample apps in this repo. I've tested using both the Objective-C and Swift versions of the sample app:

- Objective-C: https://github.com/Azure/azure-notificationhubs-ios/tree/master/Samples/Objective-C
- Swift: https://github.com/Azure/azure-notificationhubs-ios/tree/master/Samples/Swift

They both use the same basic logic.

**Comment by brannon** [comment] 2019-09-24 23:04
Based on multiple recent reports that this issue is still happening, I'm going to reopen this issue while we work through it.

**Comment by szejing547** [comment] 2019-09-25 06:51
I'm having the same issue using the iOS 13 and Xcode 11

**Comment by David4FSU** [comment] 2019-09-25 13:06
@brannon I think you may be on to something with the path. If I recall when I was trying to "update" the files, I was just deleting the .h header files out of the folder and then dragging the new ones in. This morning, I tried deleting the whole "WindowsAzureMessaging.framework" and dragging in the new one and on my first run I haven't crashed. 
I'll need to do some more testing of course but just wanted to provide that status update to help with the troubleshooting. 

And I guess I need to mention that I am not using CocoaPods, just putting the files in manually.

**Comment by szejing547** [comment] 2019-09-25 13:14
@David4FSU hi, I got the crash by reinstall my apps in iOS 13. It worked fine in iOS 12.

**Comment by sheff1422** [comment] 2019-09-26 07:30
@brannon this may help you:
![image](https://user-images.githubusercontent.com/10601271/65667489-7bc0a280-e048-11e9-8dda-0ea11f8a7838.png)

**Comment by szejing547** [comment] 2019-09-26 07:34
Apparently, the crash has gone in iOS 13.1

**Comment by sheff1422** [comment] 2019-09-26 07:37
@szejing547 not really. i got the report above from the apple review team yesterday.

**Comment by elvirberisha** [comment] 2019-09-26 08:12
Same crash as @sheff1422 and also happens on iOS 13.1, apparently this error is related with SBNotificationHubHelper.m (line 40):
`CCHmac(kCCHmacAlgSHA256, cKey, keyLength, cData, strlen(cData), cHMAC);`

This happens if you already have the app installed in the device with the Push Notifications activated, then you remove the app, reinstall it from the App Store and then you allow the Push Notifications.

**Comment by almedin-mrndic-sn** [comment] 2019-09-26 13:53
Hi @brannon 
Can you confirm that the number of crashes will be at least reduced if we upgrade to the latest version of the library, or we should wait for the final fix? 
Also, do you have an expected date when the library with the fix will be released?

**Comment by David4FSU** [comment] 2019-09-26 14:51
@brannon Just a quick follow up. My app works fine now when I properly installed the 2.0.4 version you suggested from here:  https://github.com/Azure/azure-notificationhubs-ios/releases    A tip for other, make sure you remove any existing versions before adding this one in. Thanks for the help!

**Comment by brannon** [comment] 2019-09-26 20:38
@almedin-mrndic-sn no ETA for a fix, since we haven't been able to reproduce the problem.

I've been looking at the line of code in question `SBNotificationHubHelper.m (line 40)` and I'm trying to trace backward and figure out how we could get into a state where we crash on that line.

What would be best is an isolated repro that I can run on my own device and step through the debugger to see how we get into the state causing the crash.

All of the reports (with details) are super useful, so keep them coming.

**Comment by OCP-team** [comment] 2019-09-30 08:34
We had the impression that the crash only happens to us when we are sandbox mode, when we switch to production (through a release to testflight) we have no problems with exactly the same phone we were using during the debug session. We have the same situation as said before, crash after allowing push notifications on an iPhone with iOS 13.

**Comment by Laumania** [comment] 2019-09-30 09:24
@OCP-team I see a little the same, no crash in the version in AppStore...however, my push messages ain't working either, so I think Apple is just hidding this fatal error, to avoid breaking apps in the Store.

I could be totally wrong, however, I just don't see my push notifications working at all on iOS 13 - most likely due to this.

So, are push messages working in your TestFlight version on iOS13, build with a version of Xamarin that uses XCode 11?

**Comment by OCP-team** [comment] 2019-09-30 09:43
@Laumania the version that we have in production right now still works fine on iOS 13, including receiving push notifications. Built using visual studio and xamarin forms.

**Comment by Laumania** [comment] 2019-09-30 09:49
@OCP-team But is the version you have in Prod now build against iOS 13, I mean with latest Xamarin and XCode 11?

**Comment by OCP-team** [comment] 2019-09-30 09:58
@Laumania I dug this information up for you and we are building with an azure build pipeline against Xcode 10.1. So no, there is a difference. Why this makes it possible for us to still receive push notificaitions is a mystery to me...

**Comment by Laumania** [comment] 2019-09-30 10:04
@OCP-team I'm pretty sure it's exactly because you have that version build with Xcode 10. I would assume Apple makes sure thay don't break all apps in AppStore with an iOS update, so they handle this for a periode of time.
But this clearifies that you have the same as the rest of us - which is good (no offense :P) so hopefully somebody with more knowledge about the Azure Notification Hub for iOS library can fix this.

🤞

**Comment by lehmberg** [comment] 2019-10-01 13:30
I am also getting this after upgrading to Xcode 11 and building for iOS 13. Tried the newest framework and the app does not crash as it did with the cocoa pod version but I do not get the push messages on the device.
My current version from App Store built with Xcode 10 works fine - also on iOS 13
This is a major problem as we cannot release new versions of our app without breaking push notifications

**Comment by elvirberisha** [comment] 2019-10-04 06:27
> Same crash as @sheff1422 and also happens on iOS 13.1, apparently this error is related with SBNotificationHubHelper.m (line 40):
> `CCHmac(kCCHmacAlgSHA256, cKey, keyLength, cData, strlen(cData), cHMAC);`
> 
> This happens if you already have the app installed in the device with the Push Notifications activated, then you remove the app, reinstall it from the App Store and then you allow the Push Notifications.

UPDATE: @brannon just tried to uninstall the pod (AzureNotificationHubs-iOS) and reinstall again with version 2.0.4, it seems that the problem is now solved for us, currently no crashes from the updated version in the App Store.

**Comment by lehmberg** [comment] 2019-10-04 07:59
I tried removing my pod and also installed version 2.0.4 of the framework like @brannon and my app does not crash as it did before. But I also do not get push notifications on iOS 13.

**Comment by OCP-team** [comment] 2019-10-04 12:28
@lehmberg  I have the same situation, doesn't crash anymore but I dont get the push notifications.

**Comment by eduardothiesen** [comment] 2019-10-04 13:33
My app is currently crashing in production. Xcode 11.0 and release version 2.0.4 with pod, same issue as mentioned above.

**Comment by brannon** [comment] 2019-10-04 20:57
Everyone, thanks for the detailed reports. Can I ask that each of you reply with the following info:

- iOS Version (Phone): 
- iOS Version (Deployment Target): 
- Xcode Version (at build time): 
- App Platform/Language: 
  i.e. iOS/Objective-C, iOS/Swift, iOS/Xamarin, iOS/Xamarin.Forms
- NH SDK Version: 
- How you are including the NH SDK: 
  i.e. CocoaPods, manually including Framework, building from source, etc.
- Is the app currently crashing in `registerNativeWithDeviceToken`?: 
- Are you receiving notifications?: 
  I'm interested in this for iOS 13 as well as older versions
- Are you testing with a locally built and installed App, or with an App installed from TestFlight/the AppStore?:
  This could be affecting the `aps-environment` entitlement.
- How do you send the notification?: 
  i.e. using code, Test Send page on the Azure Portal, curl/Postman/other client, etc.
- What type of notification are you sending?: 
  `alert` or `background`
- Are you setting the `apns-push-type` header when sending the notification?: 
- Are you setting the `apns-priority` header when sending the notification?: 

I know that's a lot of detail, but reading through the thread I'm having trouble following which cases are failing, which cases are working, and which cases _were_ failing but are now working.

I'm also trying to figure out who's seeing the crash and who isn't seeing the crash (but also isn't receiving notifications).

In the meantime I'm still working to reproduce the problem. I have a pretty good idea _why_ the code is crashing, but not how it's getting into that state. For the code to be crashing the way it is, something would have to be really wrong with the initialization of the SDK. And I can't necessarily fix the code to not crash without introducing other behavior changes that might be considered "breaking".

I can't get the crash to repro, but I'm using our sample app (https://github.com/Azure/azure-notificationhubs-ios/tree/master/Samples/Objective-C) which is pretty stripped down and basic.

Thanks!

**Comment by RazvanEmilR** [comment] 2019-10-04 21:04
@brannon I have this problem in Xamarin when registering with the hub. Been trying to figure this out for days. Works perfectly with iOS 12, the problem is iOS 13.1.2 in development mode and my iPhone 8 Plus.

Here are the details:
https://stackoverflow.com/questions/58230163/xamarin-ios-cannot-register-with-azure-notification-hub-in-ios-13-1-2?noredirect=1#comment102855959_58230163

**Comment by mahmutpinarbasi** [comment] 2019-10-05 09:34
Hey guys, 
It seems `2.0.4` fixed the issue for me on iOS 13.1 with Xcode 11.1 GM

**Comment by eduardothiesen** [comment] 2019-10-05 14:44
@brannon It seems 2.0.4 fixed the issue for me too. What I had to do was delete all my pods and reinstall forcing the 2.0.4 version in cocoa pods and now it's working perfectly (does not crash and I receive push notifications)

**Comment by OCP-team** [comment] 2019-10-07 09:38
@brannon 


    iOS Version (Phone): 13.1.2
    iOS Version (Deployment Target): 13.0
    Xcode Version (at build time): 11
    App Platform/Language: Xamarin.Forms
    NH SDK Version: 3.2.1
    How you are including the NH SDK: nuget
    Is the app currently crashing in registerNativeWithDeviceToken?: No
    Are you receiving notifications?: No, but I am with a phone running iOS 12
   
    Are you testing with a locally built and installed App, or with an App installed from TestFlight/the AppStore?: Locally built    
    How do you send the notification?: using code
    What type of notification are you sending?: alert
  
    Are you setting the apns-push-type header when sending the notification?: I am, putting the apns-topic as well
    Are you setting the apns-priority header when sending the notification?: I am, to 10.

**Comment by lehmberg** [comment] 2019-10-07 11:40
@brannon 

OS Version (Phone): 13.1.2
iOS Version (Deployment Target): 10.0
Xcode Version (at build time): 11
App Platform/Language: iOS / Swift
NH SDK Version: 2.0.4
How you are including the NH SDK: framework
Is the app currently crashing in registerNativeWithDeviceToken?: No
Are you receiving notifications?: Not on iOS 13+

Are you testing with a locally built and installed App, or with an App installed from TestFlight/the AppStore?: Locally built    
How do you send the notification?: using code
What type of notification are you sending?: alert

Are you setting the apns-push-type header when sending the notification? yes ["apns-push-type"] = "alert"
Are you setting the apns-priority header when sending the notification?: Yes:  ["apns-p"] = "apns-priority" = 10

**Comment by RazvanEmilR** [comment] 2019-10-07 19:17
I can confirm that push notifications now work for me in iOS 13.1.2

**Comment by mlenarto** [comment] 2019-10-22 23:02
Opened a new issue related to this one. Seeing the consistent crash with the unregisterWithDeviceToken function (not unregisterNativeWithDeviceToken). Xcode 11.1 iOS 13.1.3. Framework version 2.0.4 (latest).

**Comment by brannon** [comment] 2019-10-23 04:59
@OCP-team @lehmberg Thanks for the details! It sounds like the crash isn't occurring for you anymore. But it looks like you are aren't receiving any push notifications in your app? We received some reports that background notifications aren't being delivered on iOS 13.1+, but so far we haven't received reports that alert notifications are being dropped.

Can you provide some more details on how you are sending the notification? Which Notification Hub API are you using? Are you using one of the SDKs? Or calling the REST API directly?

@OCP-team you shouldn't have to set the `apns-topic` directly. What type of APNS credentials are you using? Certificate or Token?

**Comment by brannon** [comment] 2019-10-23 05:00
@mlenarto thanks for the report. We'll follow up on the issue you opened.

**Comment by lehmberg** [comment] 2019-10-24 10:39
@brannon It works now for me

**Comment by OCP-team** [comment] 2019-11-15 08:23
@brannon ours works now as well! We had failed to notice that the way we retrieved the deviceToken wasn't working with iOS 13 / xCode 11 anymore because of the description change (length/bytes). Thank you for your hard work!

**Comment by charvel02** [comment] 2019-12-09 15:06
@brannon 
Is there a separate issue to handle background notifications getting dropped on 13.1+? I don't see one but I just wanted to double check. We're seeing the same issue with VOIP notifications when the app is in the background or terminated. We've tested this with 2.0.3 as well as 2.0.4 and the results seem to be consistent that notifications do not get delivered on iOS 13.1+. They both work fine on older versions of iOS.

**Closed** 2020-05-20 21:30 UTC

**Comment by brannon** [comment] 2020-05-20 21:32
@charvel02 Sorry, I didn't see your response on this issue. Are you still seeing issues with notifications being delivered? If so, can you open a new issue? You can also submit a support request through the Azure portal, which will be necessary if we need to investigate your specific resources.
